//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BEY_Boletas
    {
        public int idBoleta { get; set; }
        public string Localidad { get; set; }
        public int idAsistente { get; set; }
        public bool utilizada { get; set; }
    }
}
