//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAT_PagoEstudiante
    {
        public int IDPagoEstudiante { get; set; }
        public int IDEstudiante { get; set; }
        public int IDCurso { get; set; }
        public int PagoNumero { get; set; }
        public decimal ValorPago { get; set; }
        public System.DateTime FechaProgramada { get; set; }
        public System.DateTime FechaPagada { get; set; }
        public decimal ValorInteres { get; set; }
        public decimal ValorDescuento { get; set; }
    }
}
