//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NAT_Venta
    {
        public int IDVenta { get; set; }
        public System.DateTime Fecha { get; set; }
        public Nullable<int> IDEstudiante { get; set; }
        public int IDTipoServicio { get; set; }
        public decimal Precio { get; set; }
        public double Cantidad { get; set; }
    }
}
