//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POL_V_ResumenPuntos
    {
        public int IDTorneo { get; set; }
        public int IDJugador { get; set; }
        public int IDCarton { get; set; }
        public Nullable<int> PuntosPrimeraRonda { get; set; }
        public Nullable<int> PuntosCuartos { get; set; }
        public Nullable<int> PuntosSemifinal { get; set; }
        public Nullable<int> PuntosFinal { get; set; }
    }
}
