//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POL_GrupoDetalle
    {
        public int IDGrupoDetalle { get; set; }
        public int IDGrupo { get; set; }
        public int IDEquipo { get; set; }
    }
}
