//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POL_CartonOtrasRondas
    {
        public int IDCartonOtrasRondas { get; set; }
        public int IDCarton { get; set; }
        public int Ronda { get; set; }
        public int IDEquipo1 { get; set; }
        public int IDEquipo2 { get; set; }
        public Nullable<int> Goles1 { get; set; }
        public Nullable<int> Goles2 { get; set; }
        public Nullable<int> IDEquipoPasa { get; set; }
        public string Llave { get; set; }
    }
}
