//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POL_ResultadosTorneo
    {
        public int IDResultados { get; set; }
        public int IDTorneo { get; set; }
        public int IDGrupo { get; set; }
        public int IDEquipo { get; set; }
        public int Puntos { get; set; }
        public int DifGoles { get; set; }
        public int GolesFavor { get; set; }
        public Nullable<int> Puesto { get; set; }
    }
}
