//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POL_Torneo
    {
        public int IDTorneo { get; set; }
        public string Nombre { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public int Rondas { get; set; }
        public int Grupos { get; set; }
        public int PasanxGrupo { get; set; }
        public int PasanxTercero { get; set; }
    }
}
