//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class POL_V_PuntosPrimeraRonda
    {
        public int IDTorneo { get; set; }
        public int IDJugador { get; set; }
        public int IDCarton { get; set; }
        public int IDGrupo { get; set; }
        public int IDEquipo1 { get; set; }
        public int IDEquipo2 { get; set; }
        public Nullable<int> Goles1Real { get; set; }
        public Nullable<int> Goles2Real { get; set; }
        public Nullable<int> Goles1Pronosticado { get; set; }
        public Nullable<int> Goles2Pronosticado { get; set; }
        public int Puntos { get; set; }
    }
}
