//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_Historial
    {
        public int IDHistorial { get; set; }
        public int IDUsuario { get; set; }
        public int IDCategoria { get; set; }
        public bool Correcta { get; set; }
    }
}
