//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRE_Partida
    {
        public int IDPartida { get; set; }
        public int IDUsuario1 { get; set; }
        public int IDUsuario2 { get; set; }
        public int Turno { get; set; }
        public System.DateTime Fecha { get; set; }
        public int Ronda { get; set; }
        public int PreguntasCorrectas1 { get; set; }
        public int Personajes1 { get; set; }
        public int PreguntasCorrectas2 { get; set; }
        public int Personajes2 { get; set; }
    }
}
