//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRO_MateriaPrima
    {
        public int IDMateriaPrima { get; set; }
        public string Descripcion { get; set; }
        public int IDUnidadMedida { get; set; }
        public double Inventario { get; set; }
        public decimal Costo { get; set; }
    }
}
