//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BdXtudiaWebEntities : DbContext
    {
        public BdXtudiaWebEntities()
            : base("name=BdXtudiaWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<BEY_Boletas> BEY_Boletas { get; set; }
        public virtual DbSet<BEY_Usuarios> BEY_Usuarios { get; set; }
        public virtual DbSet<CHE_Chequeo> CHE_Chequeo { get; set; }
        public virtual DbSet<CHE_Competidor> CHE_Competidor { get; set; }
        public virtual DbSet<CHE_Producto> CHE_Producto { get; set; }
        public virtual DbSet<CHE_Usuario> CHE_Usuario { get; set; }
        public virtual DbSet<EPM_Clientes> EPM_Clientes { get; set; }
        public virtual DbSet<EPM_Usuarios> EPM_Usuarios { get; set; }
        public virtual DbSet<Membership> Memberships { get; set; }
        public virtual DbSet<NAT_Aspirante> NAT_Aspirante { get; set; }
        public virtual DbSet<NAT_Curso> NAT_Curso { get; set; }
        public virtual DbSet<NAT_CursoEstudiante> NAT_CursoEstudiante { get; set; }
        public virtual DbSet<NAT_CursoHorario> NAT_CursoHorario { get; set; }
        public virtual DbSet<NAT_Estudiante> NAT_Estudiante { get; set; }
        public virtual DbSet<NAT_Localidad> NAT_Localidad { get; set; }
        public virtual DbSet<NAT_Nivel> NAT_Nivel { get; set; }
        public virtual DbSet<NAT_NotaMedica> NAT_NotaMedica { get; set; }
        public virtual DbSet<NAT_PagoEstudiante> NAT_PagoEstudiante { get; set; }
        public virtual DbSet<NAT_Profesor> NAT_Profesor { get; set; }
        public virtual DbSet<NAT_Recinto> NAT_Recinto { get; set; }
        public virtual DbSet<NAT_TipoNotaMedica> NAT_TipoNotaMedica { get; set; }
        public virtual DbSet<NAT_TipoServicio> NAT_TipoServicio { get; set; }
        public virtual DbSet<NAT_Tutor> NAT_Tutor { get; set; }
        public virtual DbSet<NAT_Venta> NAT_Venta { get; set; }
        public virtual DbSet<POL_Carton> POL_Carton { get; set; }
        public virtual DbSet<POL_CartonFinal> POL_CartonFinal { get; set; }
        public virtual DbSet<POL_CartonOtrasRondas> POL_CartonOtrasRondas { get; set; }
        public virtual DbSet<POL_CartonRonda1> POL_CartonRonda1 { get; set; }
        public virtual DbSet<POL_CartonSemiFinal> POL_CartonSemiFinal { get; set; }
        public virtual DbSet<POL_Equipo> POL_Equipo { get; set; }
        public virtual DbSet<POL_Grupo> POL_Grupo { get; set; }
        public virtual DbSet<POL_GrupoDetalle> POL_GrupoDetalle { get; set; }
        public virtual DbSet<POL_Jugador> POL_Jugador { get; set; }
        public virtual DbSet<POL_PlaneacionFinal> POL_PlaneacionFinal { get; set; }
        public virtual DbSet<POL_PlaneacionOtrasRondas> POL_PlaneacionOtrasRondas { get; set; }
        public virtual DbSet<POL_PlaneacionSemifinal> POL_PlaneacionSemifinal { get; set; }
        public virtual DbSet<POL_Resultados> POL_Resultados { get; set; }
        public virtual DbSet<POL_ResultadosTorneo> POL_ResultadosTorneo { get; set; }
        public virtual DbSet<POL_Torneo> POL_Torneo { get; set; }
        public virtual DbSet<POL_TorneoRonda1> POL_TorneoRonda1 { get; set; }
        public virtual DbSet<POL_V_PuntosCuartos> POL_V_PuntosCuartos { get; set; }
        public virtual DbSet<POL_V_PuntosFinal> POL_V_PuntosFinal { get; set; }
        public virtual DbSet<POL_V_PuntosPrimeraRonda> POL_V_PuntosPrimeraRonda { get; set; }
        public virtual DbSet<POL_V_PuntosSemifinal> POL_V_PuntosSemifinal { get; set; }
        public virtual DbSet<POL_V_Resultados1> POL_V_Resultados1 { get; set; }
        public virtual DbSet<POL_V_Resultados2> POL_V_Resultados2 { get; set; }
        public virtual DbSet<POL_V_ResultadosTorneo1> POL_V_ResultadosTorneo1 { get; set; }
        public virtual DbSet<POL_V_ResultadosTorneo2> POL_V_ResultadosTorneo2 { get; set; }
        public virtual DbSet<POL_V_ResumenPuntos> POL_V_ResumenPuntos { get; set; }
        public virtual DbSet<POL_V_ResumenPuntos2> POL_V_ResumenPuntos2 { get; set; }
        public virtual DbSet<PRE_Categoria> PRE_Categoria { get; set; }
        public virtual DbSet<PRE_Historial> PRE_Historial { get; set; }
        public virtual DbSet<PRE_Partida> PRE_Partida { get; set; }
        public virtual DbSet<PRE_PartidaDetalle> PRE_PartidaDetalle { get; set; }
        public virtual DbSet<PRE_Pregunta> PRE_Pregunta { get; set; }
        public virtual DbSet<PRE_Usuario> PRE_Usuario { get; set; }
        public virtual DbSet<PRO_Composicion> PRO_Composicion { get; set; }
        public virtual DbSet<PRO_MateriaPrima> PRO_MateriaPrima { get; set; }
        public virtual DbSet<PRO_Produccion> PRO_Produccion { get; set; }
        public virtual DbSet<PRO_ProduccionDetalle> PRO_ProduccionDetalle { get; set; }
        public virtual DbSet<PRO_UnidadMedida> PRO_UnidadMedida { get; set; }
        public virtual DbSet<PRO_Usuarios> PRO_Usuarios { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UsersInRole> UsersInRoles { get; set; }
        public virtual DbSet<UsersOpenAuthAccount> UsersOpenAuthAccounts { get; set; }
        public virtual DbSet<UsersOpenAuthData> UsersOpenAuthDatas { get; set; }
    }
}
